server:
  port: 9002
spring:
  application:
    name: PRODUCT-CATALOG-SERVICE
  datasource:
    username: thujitha
    password: *
    url: jdbc:mysql://localhost:3306/productDB
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
